### ISSUE TITLE
Loopring Protocol to prove ownership on their key

### ISSUE THREAD

**Issue by yaronvel** [WrappedBTC/DAO#3]
Loopring were not able to participate in the first and second votes.
Hence, they will prove ownership on their key by sending a tx from their address `0xd8056194369F71A98b82799132F71f34084F7660` to the DAO multisig address with empty data and value 0.

**Comment by yaronvel** [comment]
Done with this tx https://etherscan.io/tx/0x8c226b26203459af3668ee926e0fe80e41f16857aef876cd5fd82e4377ffc1ea

**Comment by mfinestone** [comment]
Sent. tx: 0x8c226b26203459af3668ee926e0fe80e41f16857aef876cd5fd82e4377ffc1ea
